In [64]:
import cv2
import numpy as np

# Load/Read image

In [65]:
img = cv2.imread(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\image_examples\Modi.jpg", 1)  # 1: color image

In [66]:
type(img)

numpy.ndarray

In [67]:
img.ndim

3

In [68]:
img.shape

(1358, 1500, 3)

In [69]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [70]:
# see image
cv2.imshow("PM", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [71]:
img.shape

(1358, 1500, 3)

# Resize Image

In [72]:
img = cv2.imread(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\image_examples\Modi.jpg", 1)
resized_image = cv2.resize(img, (679,679))

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
cv2.imshow("PM_image", gray)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [73]:
# save the image

In [74]:
cv2.imwrite("PM_image.jpg", gray)

True

# Computer Vision

- **Face detection using HaaR Cascade classifier**

In [75]:
# apply for on what you want to check

img = cv2.imread(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\image_examples\Modi.jpg", 1)

image = cv2.resize(img, (679,750))

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)



In [76]:

# Load the features

face_classifier = cv2.CascadeClassifier(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\Haarcascades\haarcascade_frontalface_default.xml")


In [77]:
faces = face_classifier.detectMultiScale(gray, 1.5, 5)

In [78]:
faces

array([[291, 118, 273, 273]])

In [79]:
if faces is():
    print("Face not found")
else:
    for(x,y,l,h) in faces:
        cv2.rectangle(image, (x,y), (x+l, y+h), (255,0,0), 5)
cv2.imshow("Face_Detection", image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\SHRI\AppData\Local\Temp\ipykernel_12300\3327820655.py:1: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is():


# Face and eye detection using HaaR Cascade classifier

In [83]:
# load the features
face_classifier = cv2.CascadeClassifier(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\Haarcascades\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\Haarcascades\haarcascade_eye.xml")


# load the image where you want to identify the features'
img = cv2.imread(r"C:\Users\SHRI\OneDrive\Desktop\DataScience_DataFiles\Image_data\image_examples\Modi.jpg", 1)

resized_image = cv2.resize(img, (679,750))

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)


# detect
faces = face_classifier.detectMultiScale(gray, 1.5, 5)

if faces is():
    print("Face not found")
else:
    for(x,y,w,h) in faces:
        cv2.rectangle(resized_image, (x,y), (x+w, y+h), (255,0,0), 2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = resized_image[y:y+h, x:x+w]

        eyes = eye_classifier.detectMultiScale(roi_gray, 1.05, 5)
        for(ex,ey, ew, eh) in eyes:
            cv2.rectangle(resized_image, (x + ex, y + ey), (x + ex + ew, y + ey + eh), (0, 255, 0), 2)
            
cv2.imshow("Face_eye_Detection", resized_image)
cv2.waitKey()
cv2.destroyAllWindows()

<>:17: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:17: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\SHRI\AppData\Local\Temp\ipykernel_12300\1077479162.py:17: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is():
